// This file is autogenerated. Changes will be overwritten.
#include "FDD3MPEXWA/moc_cabin.cpp"
#include "SJIHEP5FT5/moc_controlpanel.cpp"
#include "Z5ZXBY643D/moc_doors.cpp"
#include "MXUWEOXILK/moc_mainwindow.cpp"
#include "3PADP4P3HV/moc_lift.cpp"
